spring:
  application:
    name: animals-api
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/animals
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update